/**
 * @packageDocumentation
 * @category Mock
 */

export const EntainErrorMock = {
  throw: jest.fn(),
  handleAxiosError: jest.fn(),
};
